export const USER_ACTIONS_TYPES = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    SET_COUNT_LOGIN: 'SET_COUNT_LOGIN',
    ADD_NOTE: 'ADD_NOTE',
    REMOVE_NOTE: 'REMOVE_NOTE',
    NO_CHANGE: 'NO_CHANGE'
}